load('D:\Experiments\corticomuscular_analysis\data\real\preproc\IZO\PDH04\PDH04_IZO_eemg_onlytask_fs300_dtrnd_lf1_hf150_interp_splitDL_mc_icacl_icatdic.mat');

sig1 = EEMG.data(18, :);
sig2 = EEMG.data(129, :);
srate = EEMG.srate;

[WT1,freq] = wt_nina(sig1, srate, ...
                    'fmin', 4, 'fmax', 90, ...
                    'Preprocess', 'off', 'Wavelet', 'Morlet', 'f0', 1, ...
                    'Plot', 'off', 'CutEdges', 'on', 'nv', 30, ...
                    'event_tbl', [], 'Padding', 'none', 'fig_title', 'sig1');

[WT2] = wt_nina(sig2, srate, ...
                'fmin', 4, 'fmax', 90, ...
                'Preprocess', 'off', 'Wavelet', 'Morlet', 'f0', 1, ...
                'Plot', 'off', 'CutEdges', 'on', 'nv', 30, ...
                'event_tbl', [], 'Padding', 'none', 'fig_title', 'sig2');

[TPC, PC] = tlphcoh_nina(WT1, WT2, freq, 1, 1, srate, 0, [], [], ''); 

